config/routes.rb
Rails.application.routes.draw do
  resources :clearance_batches, only: [:index, :create]
  resources :clearance_batch_report, only: [:show]
  resources :items, only: [:index]
  root to: "clearance_batches#index"
end

app/models/clearance_batch.rb
class ClearanceBatch < ActiveRecord::Base

  has_many :items

end

app/models/item.rb
class Item < ActiveRecord::Base

  CLEARANCE_PRICE_PERCENTAGE  = BigDecimal.new("0.75")

  belongs_to :style
  belongs_to :clearance_batch

  scope :sellable, -> { where(status: 'sellable') }

  def clearance!
    clearance_price = style.wholesale_price * CLEARANCE_PRICE_PERCENTAGE

    # Set minimums for clearance prices
    if style.type == 'Pants' || style.type == 'Dress'
        if clearance_price < 5
            clearance_price = 5
        end
    else
        if clearance_price < 2
            clearance_price = 2
        end
    end

    update_attributes!(status: 'clearanced', 
                       price_sold: clearance_price)
  end

end

app/models/style.rb
class Style < ActiveRecord::Base
  self.inheritance_column = :_type_disabled
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clearance_batch_report_controller.rb
class ClearanceBatchReportController < ApplicationController
    def show
        @id = params[:id]
        @clearanced_styles = {}
        @total = 0

        @clearance_batch = ClearanceBatch.find(@id);

        # Index items by style ID and and size to calculate count of each object
        @clearance_batch.items.each do |item|
            style = Style.find(item.style_id)

            if @clearanced_styles[style.id] && @clearanced_styles[style.id][item.size]
                @clearanced_styles[style.id][item.size][:count] = @clearanced_styles[style.id][item.size][:count] + 1
            elsif @clearanced_styles[style.id]
                @clearanced_styles[style.id][item.size] = {
                    count: 1,
                    color: item.color,
                    price: item.price_sold,
                    name: style.name
                }
            else
                @clearanced_styles[style.id] = {
                    item.size => {
                        count: 1,
                        color: item.color,
                        price: item.price_sold,
                        name: style.name
                    }
                }
            end   

            @total = @total + item.price_sold  
        end
    end
end

app/controllers/clearance_batches_controller.rb
class ClearanceBatchesController < ApplicationController

  def index
    @clearance_batches  = ClearanceBatch.all
  end

  def create

    if params[:text_batch_info]
      clearancing_status = ClearancingService.new.process_text(params[:text_batch_info])
    elsif params[:csv_batch_file]
      clearancing_status = ClearancingService.new.process_file(params[:csv_batch_file].tempfile)
    end

    clearance_batch    = clearancing_status.clearance_batch
    alert_messages     = []
    if clearance_batch.persisted?
      flash[:notice]  = "#{clearance_batch.items.count} items clearanced in batch #{clearance_batch.id}"
    else
      alert_messages << "No new clearance batch was added"
    end
    if clearancing_status.errors.any?
      alert_messages << "#{clearancing_status.errors.count} item ids raised errors and were not clearanced"
      clearancing_status.errors.each {|error| alert_messages << error }
    end
    flash[:alert] = alert_messages.join("<br/>") if alert_messages.any?
    redirect_to action: :index
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def index
        @group_by = params[:group_by]
        items = Item.all

        if (@group_by == 'status')
            @groups = items.group_by { |item| item.status }
        elsif (@group_by == 'batch')
            @groups = items.group_by { |item| item.clearance_batch_id }
        end

        @group_labels = @groups.keys.compact.sort.map { |label| label.to_s }
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clearance_batch_report_helper.rb
module ClearanceBatchReportHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/clearance_batch_report/show.html.erb
<h3>Clearance Batch <%= @id %></h3>
<span> Created at: <%= l(@clearance_batch.created_at, format: :short) %></span>

<table class="table table-striped clearance_batch_report">
  <thead>
    <tr>
      <th>Style</th>
      <th>Style ID</th>
      <th>Colors</th>
      <th>Sizes</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
    <%- @clearanced_styles.each do |style_id, hash| -%>
      <%- hash.each do |size, value| -%>
        <tr>
          <td><%= value[:name] %></td>
          <td><%= style_id %></td>
          <td><%= value[:color] %></td>
          <td><%= size %></td>
          <td><%= value[:count] %></td>
          <td><%= number_to_currency(value[:price]) %></td>
          <td><%= number_to_currency(value[:price] * value[:count]) %></td>
        </tr>
      <%- end -%>
    <%- end -%>
    <tr id='total'>
      <td> Total </td>
      <td></td>
      <td></td>
      <td></td>
      <td><%= @clearance_batch.items.count %></td>
      <td></td>
      <td><%= number_to_currency(@total) %></td>
    </tr>
  </tbody>
</table>

app/views/clearance_batches/index.html.erb
<h2>Create a new batch</h2>
<p> Upload a CSV file or scan items (one item per line) to create a batch of items to be clearanced. </p>

<%= form_tag(clearance_batches_path, multipart: true, class: 'form-inline', role: 'form') do %>
  <div class="form-group">
    <%= label_tag 'csv_batch_file', 'Select batch file:' %>
    <%= file_field_tag 'csv_batch_file', class: 'form-control' %>
  </div>
  <%= button_tag 'upload batch file', class: 'btn btn-primary' %>
<% end %>

<%= form_tag(clearance_batches_path, multipart: true, class: 'form-inline', role: 'form') do %>
  <div class="form-group">
    <%= label_tag 'text_batch_info', 'Enter batch information:' %>
    <%= text_area_tag 'text_batch_info', nil, rows: 10, cols: 40 %>
  </div>
  <%= button_tag 'upload batch info', class: 'btn btn-primary' %>
<% end %>

<h2>Clearance Batches</h2>
<table class="table table-striped clearance_batches">
  <thead>
    <tr>
      <th></th>
      <th>Date clearanced</th>
      <th>Number of items clearanced</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%- @clearance_batches.each do |clearance_batch| -%>
      <tr>
        <td>Clearance Batch <%= clearance_batch.id %></td>
        <td><%= l(clearance_batch.created_at, format: :short) %></td>
        <td><%= clearance_batch.items.count %></td>
        <td><%= link_to 'View Report', clearance_batch_report_path(clearance_batch.id) %></td>
      </tr>
    <%- end -%>
  </tbody>
</table>

app/views/items/index.html.erb
<p> Jump to:
  <%- @group_labels.each do |label| -%>
    <%- if label -%> 
      <a class='category_link' href='#<%= label %>'> <%= label.capitalize %> </a>
     <%- end %>
  <%- end %>
</p>

<%- @groups.each do |key, items| -%>
  <%- if key -%> 
    <h3>
     <a name='<%= key %>' class='anchor'> <%= @group_by.capitalize %>: <%= key.to_s.capitalize %> </a>
    </h3>
    <table class="table table-striped">
      <thead>
        <tr>
          <th> Item ID </th>
          <th> Style Name </th>
          <th> Style ID </th>
          <th> Size </th>
          <th> Color </th>
          <%- if items[0].price_sold -%>
            <th> Price Sold </th>
          <%- end -%>
          <%- if key == 'sellable' -%>
            <th> Retail Price </th>
            <th> Wholesale Price </th>
          <%- end -%>
          <%- if key == 'clearanced' -%>
            <th> Clearance Batch ID </th>
          <%- end -%>
        </tr>
      </thead>
      <tbody>
        <%- items.each do |item| -%>
          <tr>
            <td><%= item.id %></td>
            <td><%= Style.find(item.style_id).name %></td>
            <td><%= item.style_id %></td>
            <td><%= item.size %></td>
            <td><%= item.color %></td>
            <%- if item.price_sold -%>
              <td><%= number_to_currency(item.price_sold) %></td>
            <%- end -%>
            <%- if key == 'sellable' -%>
              <td><%= number_to_currency(Style.find(item.style_id).retail_price) %></td>
              <td><%= number_to_currency(Style.find(item.style_id).wholesale_price) %></td>
            <%- end -%>
            <%- if key == 'clearanced' -%>
              <td><%= item.clearance_batch_id %></td>
            <%- end -%>
          </tr>
        <%- end -%>
      </tbody>
    </table>
  <%- end -%>
<%- end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TakeHomeChallenge</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <h1>Stitch Fix Clearance Tool</h1>
  <p><%= link_to 'Back to home', clearance_batches_path %></p>
  <p> Browse all items by:
    <span class="items_link"><%= link_to 'Status', items_path(:group_by => 'status') %></span>
    <span class="items_link"><%= link_to 'Clearance Batch', items_path(:group_by => 'batch') %></span>
  </p>
  <%- if flash[:notice] -%>
    <div class="alert alert-info" role="alert">
      <%= flash[:notice].html_safe %>
    </div>
  <%- end -%>
  <%- if flash[:alert] -%>
    <div class="alert alert-danger" role="alert">
      <%= flash[:alert].html_safe %>
    </div>
  <%- end -%>
  <%= yield %>
</div>

</body>
</html>